// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbzawuisboqzcdjmcvgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiemF3dWlzYm9xemNkam1jdmdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5ODI0NDYsImV4cCI6MjA1MDU1ODQ0Nn0.T5R6x3PmiSxKuIjyXzq7Ujte33Zasn-EQ40_5kBLELc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);